kind: Namespace
apiVersion: v1
metadata:
  name: dev
  labels:
    environment: dev
---
apiVersion: v1
kind: Pod
metadata:
  name: centos
  namespace: dev
  labels:
    app: centos
spec:
  restartPolicy: OnFailure
  containers:
  - name: centos
    image: centos:latest
    # spin & wait indefinitely
    command: ["/bin/sh", "-c", "trap : TERM INT; sleep infinity & wait"]
    resources: {}
  nodeSelector:
    kubernetes.io/os: linux