apiVersion: v1
kind: Pod
metadata:
  name: netshoot
  labels:
    app: netshoot
spec:
  nodeSelector:
    kubernetes.io/os: linux
  containers:
    - name: netshoot
      command: ["/bin/sh", "-c", "trap : TERM INT; sleep infinity & wait"]
      image: nicolaka/netshoot:latest
      resources: {}
