---
## This playbook deploys the whole application stack in this site.

# ping all hosts
- hosts: nodes
  roles:
  - ping

# Apply common configuration to all hosts
- hosts: nodes
  roles:
  - common_centos

# Configure master nodes
- hosts: masters
  roles:
  - master_centos

  # tags:
  # - master

# Configure worker nodes
- hosts: workers
  roles:
  - worker_centos

  # tags:
  # - worker

# Updated API server allowed SANS endpoints
- hosts: masters
  roles:
  - update_api_ep

  # tags:
  # - master
