---
# This role contains master handlers that will run on all master nodes.

# Setup a handler for checking Docker daemon using the below code.
- name: docker status
  service: name=docker state=started
