apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: additional-calico-network-1
spec:
  config: '{
      "cniVersion": "0.3.1",
      "type": "calico",
      "log_level": "info",
      "datastore_type": "kubernetes",
      "mtu": 1410,
      "nodename_file_optional": false,
      "ipam": {
        "type": "calico-ipam",
        "assign_ipv4" : "true",
        "assign_ipv6" : "false",
        "ipv4_pools": ["10.244.64.0/20", "cali1-ippool"]
      },
      "policy": {
          "type": "k8s"
      },
      "kubernetes": {
          "kubeconfig": "/etc/cni/net.d/calico-kubeconfig"
      }
    }'
---

apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: additional-calico-network-2
spec:
  config: '{
      "cniVersion": "0.3.1",
      "type": "calico",
      "log_level": "info",
      "datastore_type": "kubernetes",
      "mtu": 1410,
      "nodename_file_optional": false,
      "ipam": {
        "type": "calico-ipam",
        "assign_ipv4" : "true",
        "assign_ipv6" : "false",
        "ipv4_pools": ["10.244.80.0/20", "cali2-ippool"]
      },
      "policy": {
          "type": "k8s"
      },
      "kubernetes": {
          "kubeconfig": "/etc/cni/net.d/calico-kubeconfig"
      }
    }'
---
