apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: ubuntu-mysql
spec:
  running: false
  template:
    metadata:
      labels:
        kubevirt.io/size: small
        kubevirt.io/domain: ubuntu-mysql
    spec:
      domain:
        cpu:
          cores: 2
        devices:
          disks:
            - name: containerdisk
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
          interfaces:
          - name: default
            masquerade: {}
        resources:
          requests:
            memory: 4096Mi
      networks:
      - name: default
        pod: {}
      volumes:
        - name: containerdisk
          containerDisk:
            image: tedezed/ubuntu-container-disk:22.0
        - name: cloudinitdisk
          cloudInitNoCloud:
            # if this section exceeds 2048 characters, you'll have to use k8s secret and reference the secret instead of having the data inline
            userDataBase64: ${CLOUDINIT}
            # example to reference secret
            #secretRef:
              #name: my-vmi-secret
---
apiVersion: v1
kind: Service
metadata:
  name: ubuntu-ssh
spec:
  ports:
  - port: 22
    targetPort: 22
    protocol: TCP
    nodePort: 30322
  selector:
    kubevirt.io/domain: ubuntu-mysql
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: ubuntu-nginx
spec:
  ports:
  - port: 3306
    targetPort: 3306
    protocol: TCP
  selector:
    kubevirt.io/domain: ubuntu-mysql
